-- 100 real ICD-10-CM codes, fetched from the NLM Clinical Tables API
-- (https://clinicaltables.nlm.nih.gov/api/icd10cm/v3/search). Idempotent: safe to re-run.
INSERT INTO diagnosis_codes (code, description) VALUES
  ('E11.8', 'Type 2 diabetes mellitus with unspecified complications'),
  ('E11.9', 'Type 2 diabetes mellitus without complications'),
  ('E11.A', 'Type 2 diabetes mellitus without complications in remission'),
  ('E11.00', 'Type 2 diabetes mellitus with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma (NKHHC)'),
  ('E11.01', 'Type 2 diabetes mellitus with hyperosmolarity with coma'),
  ('E11.10', 'Type 2 diabetes mellitus with ketoacidosis without coma'),
  ('E11.11', 'Type 2 diabetes mellitus with ketoacidosis with coma'),
  ('E11.21', 'Type 2 diabetes mellitus with diabetic nephropathy'),
  ('E78.1', 'Pure hyperglyceridemia'),
  ('E78.2', 'Mixed hyperlipidemia'),
  ('E78.3', 'Hyperchylomicronemia'),
  ('E78.5', 'Hyperlipidemia, unspecified'),
  ('E78.6', 'Lipoprotein deficiency'),
  ('E78.9', 'Disorder of lipoprotein metabolism, unspecified'),
  ('E03.0', 'Congenital hypothyroidism with diffuse goiter'),
  ('E03.1', 'Congenital hypothyroidism without goiter'),
  ('E03.2', 'Hypothyroidism due to medicaments and other exogenous substances'),
  ('I10', 'Essential (primary) hypertension'),
  ('I25.2', 'Old myocardial infarction'),
  ('I25.3', 'Aneurysm of heart'),
  ('I25.5', 'Ischemic cardiomyopathy'),
  ('I25.6', 'Silent myocardial ischemia'),
  ('I25.9', 'Chronic ischemic heart disease, unspecified'),
  ('I25.10', 'Atherosclerotic heart disease of native coronary artery without angina pectoris'),
  ('I48.0', 'Paroxysmal atrial fibrillation'),
  ('I48.3', 'Typical atrial flutter'),
  ('I48.4', 'Atypical atrial flutter'),
  ('I48.11', 'Longstanding persistent atrial fibrillation'),
  ('I48.19', 'Other persistent atrial fibrillation'),
  ('I50.1', 'Left ventricular failure, unspecified'),
  ('I50.9', 'Heart failure, unspecified'),
  ('I50.20', 'Unspecified systolic (congestive) heart failure'),
  ('I50.21', 'Acute systolic (congestive) heart failure'),
  ('I50.22', 'Chronic systolic (congestive) heart failure'),
  ('J45.20', 'Mild intermittent asthma, uncomplicated'),
  ('J45.21', 'Mild intermittent asthma with (acute) exacerbation'),
  ('J45.22', 'Mild intermittent asthma with status asthmaticus'),
  ('J45.30', 'Mild persistent asthma, uncomplicated'),
  ('J45.31', 'Mild persistent asthma with (acute) exacerbation'),
  ('J45.32', 'Mild persistent asthma with status asthmaticus'),
  ('J45.40', 'Moderate persistent asthma, uncomplicated'),
  ('J45.41', 'Moderate persistent asthma with (acute) exacerbation'),
  ('J18.0', 'Bronchopneumonia, unspecified organism'),
  ('J18.1', 'Lobar pneumonia, unspecified organism'),
  ('J18.2', 'Hypostatic pneumonia, unspecified organism'),
  ('J18.8', 'Other pneumonia, unspecified organism'),
  ('J18.9', 'Pneumonia, unspecified organism'),
  ('J44.0', 'Chronic obstructive pulmonary disease with (acute) lower respiratory infection'),
  ('J44.1', 'Chronic obstructive pulmonary disease with (acute) exacerbation'),
  ('J44.9', 'Chronic obstructive pulmonary disease, unspecified'),
  ('J44.81', 'Bronchiolitis obliterans and bronchiolitis obliterans syndrome'),
  ('K21.9', 'Gastro-esophageal reflux disease without esophagitis'),
  ('K21.00', 'Gastro-esophageal reflux disease with esophagitis, without bleeding'),
  ('K21.01', 'Gastro-esophageal reflux disease with esophagitis, with bleeding'),
  ('K29.00', 'Acute gastritis without bleeding'),
  ('K29.01', 'Acute gastritis with bleeding'),
  ('K29.20', 'Alcoholic gastritis without bleeding'),
  ('K29.21', 'Alcoholic gastritis with bleeding'),
  ('K29.30', 'Chronic superficial gastritis without bleeding'),
  ('M54.2', 'Cervicalgia'),
  ('M54.6', 'Pain in thoracic spine'),
  ('M54.9', 'Dorsalgia, unspecified'),
  ('M54.00', 'Panniculitis affecting regions of neck and back, site unspecified'),
  ('M54.01', 'Panniculitis affecting regions of neck and back, occipito-atlanto-axial region'),
  ('M54.02', 'Panniculitis affecting regions of neck and back, cervical region'),
  ('M54.03', 'Panniculitis affecting regions of neck and back, cervicothoracic region'),
  ('M17.0', 'Bilateral primary osteoarthritis of knee'),
  ('M17.2', 'Bilateral post-traumatic osteoarthritis of knee'),
  ('M17.4', 'Other bilateral secondary osteoarthritis of knee'),
  ('M17.5', 'Other unilateral secondary osteoarthritis of knee'),
  ('M17.9', 'Osteoarthritis of knee, unspecified'),
  ('M17.10', 'Unilateral primary osteoarthritis, unspecified knee'),
  ('N39.0', 'Urinary tract infection, site not specified'),
  ('N39.3', 'Stress incontinence (female) (male)'),
  ('N39.8', 'Other specified disorders of urinary system'),
  ('N39.9', 'Disorder of urinary system, unspecified'),
  ('F41.0', 'Panic disorder [episodic paroxysmal anxiety]'),
  ('F41.1', 'Generalized anxiety disorder'),
  ('F41.3', 'Other mixed anxiety disorders'),
  ('F41.8', 'Other specified anxiety disorders'),
  ('F41.9', 'Anxiety disorder, unspecified'),
  ('F32.0', 'Major depressive disorder, single episode, mild'),
  ('F32.1', 'Major depressive disorder, single episode, moderate'),
  ('F32.2', 'Major depressive disorder, single episode, severe without psychotic features'),
  ('F32.3', 'Major depressive disorder, single episode, severe with psychotic features'),
  ('F32.4', 'Major depressive disorder, single episode, in partial remission'),
  ('G43.A0', 'Cyclical vomiting, in migraine, not intractable'),
  ('G43.A1', 'Cyclical vomiting, in migraine, intractable'),
  ('G43.B0', 'Ophthalmoplegic migraine, not intractable'),
  ('G43.B1', 'Ophthalmoplegic migraine, intractable'),
  ('G43.C0', 'Periodic headache syndromes in child or adult, not intractable'),
  ('G43.C1', 'Periodic headache syndromes in child or adult, intractable'),
  ('S72.001A', 'Fracture of unspecified part of neck of right femur, initial encounter for closed fracture'),
  ('S72.001B', 'Fracture of unspecified part of neck of right femur, initial encounter for open fracture type I or II'),
  ('S72.001C', 'Fracture of unspecified part of neck of right femur, initial encounter for open fracture type IIIA, IIIB, or IIIC'),
  ('S72.001D', 'Fracture of unspecified part of neck of right femur, subsequent encounter for closed fracture with routine healing'),
  ('S52.001A', 'Unspecified fracture of upper end of right ulna, initial encounter for closed fracture'),
  ('S52.001B', 'Unspecified fracture of upper end of right ulna, initial encounter for open fracture type I or II'),
  ('S52.001C', 'Unspecified fracture of upper end of right ulna, initial encounter for open fracture type IIIA, IIIB, or IIIC'),
  ('S52.001D', 'Unspecified fracture of upper end of right ulna, subsequent encounter for closed fracture with routine healing')
ON CONFLICT (code) DO NOTHING;
