"""create diagnosis_codes, consultations and consultation_diagnoses

Revision ID: 14c9e1658057
Revises:
Create Date: 2026-09-22 10:21:17.431160

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14c9e1658057"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consultations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_name", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consultations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consultations_patient_name"), ["patient_name"], unique=False
        )

    op.create_table(
        "diagnosis_codes",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "consultation_diagnoses",
        sa.Column("consultation_id", sa.Integer(), nullable=False),
        sa.Column("diagnosis_code", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["consultation_id"], ["consultations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["diagnosis_code"],
            ["diagnosis_codes.code"],
        ),
        sa.PrimaryKeyConstraint("consultation_id", "diagnosis_code"),
    )
    with op.batch_alter_table("consultation_diagnoses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consultation_diagnoses_diagnosis_code"), ["diagnosis_code"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("consultation_diagnoses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consultation_diagnoses_diagnosis_code"))

    op.drop_table("consultation_diagnoses")
    op.drop_table("diagnosis_codes")
    with op.batch_alter_table("consultations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consultations_patient_name"))

    op.drop_table("consultations")
    # ### end Alembic commands ###
